### ISSUE TITLE
number of samples in whole dataset vs subset

### ISSUE THREAD

**Issue by nullmightybofo** [cpra/dlvc2018#1]
Is this supposed to the number of samples in the whole dataset or in the currently used subset (i.e., training, validation or test, whatever the object was instantiated for)?

https://github.com/cpra/dlvc2018/blob/c4bc10284d2d35e4b02d16ae8b17184f59e22dd0/assignments/reference/dlvc/datasets/pets.py#L31

Thanks

**Comment by martinmatak** [comment]
It seems to me as the number of samples in the currently used subset. If it would be number of total samples in all three subsets, it would be hard-coded.

**Comment by nullmightybofo** [comment]
Thanks for your answer. It would seem to make more sense this way. It's just that it should say "number of samples in the subset" to more precise, I guess. Same thing actually goes for the __getitem__ method's docstring.

**Comment by martinmatak** [comment]
Well, it depends how you look at it.. After all, the name of the class is `PetsDataset` so it is a dataset :)
