### ISSUE TITLE
Batch class: label vs labels as property name

### ISSUE THREAD

**Issue by nullmightybofo** [cpra/dlvc2018#2]
I don't yet know if that matters at all but the property `label` in class `Batch` is called `labels` in the docstring of `BatchGenerator`. Is this accessed anywhere in the code later on?

https://github.com/cpra/dlvc2018/blob/c4bc10284d2d35e4b02d16ae8b17184f59e22dd0/assignments/reference/dlvc/batches.py#L18

**Comment by martinmatak** [comment]
We (group 15) did change it to `labels` manually (since label**s** are stored here). Could it be that it's just a typo in the variable name?

**Comment by nullmightybofo** [comment]
Yep I guess so. Thanks again.

**Comment by cpra** [comment]
Sorry I missed that discussion. That's an error in the comment, I'll fix it. I reverted all point reductions of groups who renamed `self.label` to `self.labels` (2 groups).
