### ISSUE TITLE
getitem for single indices vs for slices

### ISSUE THREAD

**Issue by nullmightybofo** [cpra/dlvc2018#3]
From the given docstring I take it that we should make this work for returing data (an image) giving a single index, like so for a `PetsDataset` object mypets:

img_data = mypets[3]

Are we supposed to make this work also for a range of indices, like so:

images = mypets[3:7]

?

Its mroe of a question of how some of you have implemented this...

BR

https://github.com/cpra/dlvc2018/blob/c4bc10284d2d35e4b02d16ae8b17184f59e22dd0/assignments/reference/dlvc/datasets/pets.py#L40

**Comment by martinmatak** [comment]
We implemented it so that it works for a single index, e.g. ``img_datata = mypets[3]`` works.

**Comment by nullmightybofo** [comment]
thanks, also did it like this as I think the other version is not necessary (for us).
