### ISSUE TITLE
scipy allowed?

### ISSUE THREAD

**Issue by nullmightybofo** [cpra/dlvc2018#8]
General info says:

"You are free to use all functionality provided by the Python standard library and numpy."

https://github.com/cpra/dlvc2018/blob/master/assignments/general.md

I guess scipy is also OK? (useful for some image processing related to data augmentation). 

Thanks

**Comment by cpra** [comment]
what for? opencv should have all you need and more.

**Comment by nullmightybofo** [comment]
Indeed! It's just that I can't use opencv on the machine I am training on (I have insufficient rights on that machine to make it work; it's a problem with libraries).
So I guess I'll try the "official" servers later on and make final tests with opencv, shouldn't make a difference to doing it with scipy.

Thanks for taking time to answer.
